import { useEffect, useState } from "react";
import axios from "axios";

const API = process.env.REACT_APP_API_URL;

function Favorites() {

  const user = JSON.parse(
    localStorage.getItem("user")
  );

  const [favorites, setFavorites] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {

    if (user?.email) {
      fetchFavorites();
    } else {
      setLoading(false);
    }

  }, [user]);

  const fetchFavorites = async () => {

    try {

      const token =
      localStorage.getItem("token");  

      console.log("TOKEN =", token);

      const response = await axios.get(
        `${API}/favorites/${user.email}`,

        {
        headers: {
          Authorization:
          `Bearer ${token}`
        }
      }

      );

      setFavorites(response.data);

    } catch (error) {

      console.error(error);

    } finally {

      setLoading(false);

    }
  };

  if (!user) {

  return (

    <div
      style={{
        minHeight: "100vh",
        background:
          "linear-gradient(135deg,#FFE8F3 0%,#F7E8FF 50%,#EEF5FF 100%)",
        padding: "50px",
        fontFamily: "Arial, sans-serif",
      }}
    >

      <div
        style={{
          maxWidth: "1100px",
          margin: "0 auto",
        }}
      >

        <div
          style={{
            textAlign: "center",
            marginBottom: "50px",
          }}
        >
          <h1
            style={{
              fontSize: "42px",
              background:
                "linear-gradient(90deg,#ff4d8d,#9b5cff)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              fontWeight: "bold",
            }}
          >
            ❤️ My Favorite Products
          </h1>

          <p
            style={{
              fontSize: "18px",
              color: "#555",
              lineHeight: "1.8",
              maxWidth: "800px",
              margin: "20px auto",
            }}
          >
            Save your favorite beauty products and access them anytime.
            Build your own personalized beauty collection with AI-recommended
            foundations, lipsticks, blushes, and skincare products that match
            your skin tone and preferences.
          </p>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))",
            gap: "25px",
            marginBottom: "50px",
          }}
        >

          <div style={cardStyle}>
            <div style={{ fontSize: "60px" }}>💄</div>

            <h3>Save Makeup Products</h3>

            <p>
              Keep your favorite foundations, lipsticks, and blushes in one
              convenient place.
            </p>
          </div>

          <div style={cardStyle}>
            <div style={{ fontSize: "60px" }}>❤️</div>

            <h3>Personal Wishlist</h3>

            <p>
              Create your own beauty wishlist and quickly revisit products you
              love.
            </p>
          </div>

          <div style={cardStyle}>
            <div style={{ fontSize: "60px" }}>✨</div>

            <h3>AI Recommendations</h3>

            <p>
              Save personalized product recommendations generated by GlowMatch
              AI for future use.
            </p>
          </div>

        </div>

        <div
          style={{
            background: "rgba(255,255,255,0.85)",
            backdropFilter: "blur(12px)",
            borderRadius: "25px",
            padding: "35px",
            textAlign: "center",
            boxShadow: "0 12px 30px rgba(0,0,0,.1)",
          }}
        >

          <h2 style={{ color: "#ff4d8d" }}>
            🔒 Login Required
          </h2>

          <p
            style={{
              fontSize: "17px",
              color: "#666",
              lineHeight: "1.7",
            }}
          >
            Please log in to view your favorite beauty products, manage your
            personalized wishlist, and continue exploring AI-powered beauty
            recommendations with GlowMatch AI.
          </p>

        </div>

      </div>

    </div>

  );

}

  if (loading) {

    return (
      <div style={{ padding: "40px" }}>
        <h2>Loading Favorites...</h2>
      </div>
    );
  }

  return (

    <div
     style={{
       minHeight: "100vh",
       padding: "40px",
       background:
           "linear-gradient(135deg,#FFE8F3 0%,#F7E8FF 50%,#EEF5FF 100%)",
       fontFamily: "Arial, sans-serif",
      }}
    >

     <div
  style={{
    textAlign: "center",
    marginBottom: "35px",
  }}
>
  <h1
    style={{
      fontSize: "40px",
      marginBottom: "12px",
      background:
        "linear-gradient(90deg,#ff4d8d,#9b5cff)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      fontWeight: "bold",
    }}
  >
    ❤️ My Favorite Beauty Products
  </h1>

  <p
    style={{
      fontSize: "18px",
      color: "#666",
      marginBottom: "6px",
    }}
  >
    Welcome back,
    <strong style={{ color: "#ff4d8d" }}>
      {" "}{user.name}
    </strong>
  </p>

  <p
    style={{
      color: "#777",
      fontSize: "15px",
      maxWidth: "650px",
      margin: "0 auto",
      lineHeight: "1.6",
    }}
  >
    View all your saved makeup and skincare products in one place. Your favorite recommendations are always ready whenever you need them.
  </p>
</div>

      {favorites.length === 0 ? (

        <p>No favorite products yet.</p>

      ) : (

        favorites.map((item, index) => (

          <div
            key={index}
            style={{
              border: "1px solid #ddd",
              borderRadius: "10px",
              padding: "20px",
              marginBottom: "15px"
            }}
          >

            <img
              src={item.image}
              alt={item.product_name}
              width="120"
            />

            <h3>{item.product_name}</h3>

            <p>
              Brand: {item.brand}
            </p>

            <p>
              Category: {item.category}
            </p>

            <p>
              Price: ${item.price}
            </p>

          </div>

        ))

      )}

    </div>
  );
}

const cardStyle = {
  background: "rgba(255,255,255,0.82)",
  backdropFilter: "blur(12px)",
  padding: "25px",
  borderRadius: "20px",
  textAlign: "center",
  boxShadow: "0 10px 25px rgba(0,0,0,.1)",
};

export default Favorites;
